### ISSUE TITLE
Change GitHub "About" section to reflect supported OSes?

### ISSUE THREAD

**Issue by maxcohn** [hoodie/notify-rust#101]
Right now, the "About" section on GitHub says:

> Send Desktop Notifications on linux and bsd

I initially moved on from looking at this library as I was looking for full cross platform support, but I later realized that later in the README it mentions Windows and OSX support. Could the "About" be updated to something reflecting that? A few ideas:

* Send desktop notifications on all major operating systems
* Send desktop notifications on Linux, BSD, OSX, and Windows

**Comment by hoodie** [comment]
I'm usually more on the humble side, but you are absolutely right :P
