### ISSUE TITLE
DBus reason of closing

### ISSUE THREAD

**Issue by tonyshkurenko** [hoodie/notify-rust#104]
Please, do not ignore this value here: https://github.com/hoodie/notify-rust/blob/3ab49e7f2e04d817ed12aef6eb2dc65e2b4f727e/src/xdg/dbus_rs.rs#L233

According to the spec: https://specifications.freedesktop.org/notification-spec/latest/ar01s09.html

![image](https://user-images.githubusercontent.com/8597964/116361177-5b029500-a809-11eb-8d25-a34725cee0a2.png)

The second param it's the only way to handle click on notification itself

**Comment by hoodie** [comment]
oh cool, thanks for pointing this out, I hadn't noticed that yet

**Comment by hoodie** [comment]
@tonyshkurenko how about this?

**Comment by hoodie** [comment]
actually, since you mention "The second param it's the only way to handle click on notification itself" what Desktop environment are you using? because the under KDE at least clicking on the notification triggers the `"default"` action".

**Comment by tonyshkurenko** [comment]
I tested on xfce4 and gnome. Thanks for your help!

**Comment by hoodie** [comment]
thank you for pointing this out

**Comment by hoodie** [comment]
could you post the code you tried please?

**Comment by hoodie** [comment]
also: if you like you could open a PR that fixes that

**Comment by tonyshkurenko** [comment]
I will file a PR then :)

**Comment by tonyshkurenko** [comment]
Regarding code I've tried, I simplified it a bit, but generally it's:

```
notify_rust::handle_action(uid, |action: &notify_rust::xdg::ActionResponse| {
    match action {
        notify_rust::xdg::ActionResponse::Custom(key) => ...,
        notify_rust::xdg::ActionResponse::Closed(reason) => ...,
    }
});
```

After PR it's possible now to do:

```
```
notify_rust::handle_action(uid, |action: &notify_rust::ActionResponse| {
    match action {
        notify_rust::ActionResponse::Custom(key) => ...,
        notify_rust::ActionResponse::Closed(reason) => ...,
    }
});
```
```

**Comment by hoodie** [comment]
I hadn't `realized` this at the time, but why do you even use `notify_rust::handle_action`? there is `.wait_for_action()`
I was even thinking about deprecating the free function api, is there any good reason not to?
