### ISSUE TITLE
Sudo

### ISSUE THREAD

**Issue by Delta-Azura** [hoodie/notify-rust#111]
Hi bro. I have a problem. 
I am working on a pacman wrapper for arch linux so i have to use sudo to launch this package manager.
But unfortunately when i use sudo, your notifier didn't work. If you have a solution ;-) 
Good job and great continuation 

(sorry for my  english :-(    )

**Comment by Delta-Azura** [comment]
i fixed the problem. But great job :-)

**Comment by hoodie** [comment]
good to hear, how did you do it?

**Comment by Delta-Azura** [comment]
Finally no :-( i opened an another issue. i solved this problem with my linux distro (i launched my programm with systemctl --user).
