### ISSUE TITLE
Sudo or root

### ISSUE THREAD

**Issue by ghost** [hoodie/notify-rust#112]
Hi. Unfortunately, in my script i need to use sudo to get root access but notify-rust didn't work when you are using root account or sudo.

**Comment by rnestler** [comment]
I had a similar issue and solved it by switching back to the original user and setting DBUS_SESSION_BUS_ADDRESS explicitly:
`sudo -u $SUDO_USER DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$SUDO_UID/bus /usr/bin/reboot-arch-btw`.

See also the discussion at https://github.com/rnestler/reboot-arch-btw/issues/33
