### ISSUE TITLE
Update notification while waiting on action

### ISSUE THREAD

**Issue by Joshuao95** [hoodie/notify-rust#135]
Hiya,

I was wondering if there's any way I've missed to update a notification while it's waiting on an action/closed?

My use case is that I'd like to do something when the user closes the notification, but if they haven't seen it yet I'd like to keep it being updated with the latest information.

I can stick the wait_for_action in a thread for itself, but it consumes the NotificationHandle, so I can't then update it.

Cheers

**Comment by hoodie** [comment]
Technically you don't need to hold the `NotificationHandle` to update the notification, you can look at the id you get back from sending and use that too. The `NotificationHandle` is just to make that convenient. look at the [update example](https://github.com/hoodie/notify-rust/blob/main/examples/update.rs#L30)

**Comment by Joshuao95** [comment]
Aha! Thanks for that, missed the examples there. Cheers!
