### ISSUE TITLE
ZBus Error

### ISSUE THREAD

**Issue by Pandawan** [hoodie/notify-rust#140]
This is probably an issue on my side but you're more knowledgeable than me on this stuff.

I used to have a Linux CI/CD (on GitHub Actions) working perfectly fine to run this, but ever since a few days ago, I've been having the error: 
> Error { kind: Zbus(Io(Os { code: 2, kind: NotFound, message: "No such file or directory" })) }

I'm assuming this means there's some kind of config file that's missing somewhere to enable the notification system through dbus. I don't know much about Zbus/Dbus but seeing from your own config, simply having `libdbus-1-dev` should be enough? 

So I'm wondering if maybe something changed in notify-rust related to that? And if not, maybe you have some insight for what I could look into? 

Thanks

**Comment by hoodie** [comment]
You technically only need `libdbus-1-dev` if you're compiling with the dbus-rs dependency enabled, that is no longer the default. AFAIK zbus is completely independent of what you might have on your system (@zeenix might be able to confirm this statement).
With these `"No such file or directory"` errors it's always a bit hard to tell, sometimes you get those when the programm is trying to shell out or open a socket, maybe dbus/zbus have to use a specific system file (virtual file) to connect to the bus and it can't find that. You can tell, at this point I can really only speculate, unless you have a proper backtrace.

BTW: for these kinda issues I enabled [**Discussions**](https://github.com/hoodie/notify-rust/discussions/new?category=q-a) feature in this repo, maybe we should take it over there.

**Comment by zeenix** [comment]
> AFAIK zbus is completely independent of what you might have on your system (@zeenix might be able to confirm this statement).

Confirmed. We only require `DBUS_SESSION_BUS_ADDRESS` to be correctly set for the session bus and the bus to be actually running.

**Comment by zeenix** [comment]
> You technically only need `libdbus-1-dev` if you're compiling with the dbus-rs dependency enabled, that is no longer the default.

@hoodie Maybe it's time to reduce the complexity and drop the `dbus-rs` dep and code all together?

**Comment by hoodie** [comment]
I've been a bit reluctant to remove it, I mostly because I've had a user or two in the past who asked me not to update the MSRV because their shipping the library in some distribution, and zbus is usually pretty up with compiler features.

**Comment by zeenix** [comment]
> I've been a bit reluctant to remove it, I mostly because I've had a user or two in the past who asked me not to update the MSRV because their shipping the library in some distribution, and zbus is usually pretty up with compiler features.

Fair enough. I've actually been trying not to use the latest and greatest features but sometimes there are new std API that I needed 2 years ago so it's hard to not jump on them as soon as they're stabalized. :) Having said that, I'm not planning on using latest features in 2.0 cycle.
