### ISSUE TITLE
[Feature Request] A way to ask for permission for notifications

### ISSUE THREAD

**Issue by daggy1234** [hoodie/notify-rust#143]
I'm building a desktop ui with iced-rs and I was hoping I could find a way to ask for notifications. When the app is installed, I cannot send notifications with notify-rs on both macos and windows because I need to ask for said permission. Is there a guide on how I would implement this on first time running or is there an alternative package/technique I could use.

https://github.com/Daggy1234/discord-rpc-gui

**Comment by Pandawan** [comment]
For macOS, you don't currently need permissions. So if you're not seeing any notifications you should look at/post an issue on [mac-notification-sys](https://github.com/h4llow3En/mac-notification-sys) (which is what notify-rust uses under the hood).
