### ISSUE TITLE
winrt-notification is not maintained

### ISSUE THREAD

**Issue by lucasfernog** [hoodie/notify-rust#148]
The winrt-notification does not seem to be maintained and uses an outdated and vulnerable windows version (see [the GitHub advisory](https://github.com/advisories/GHSA-x4mq-m75f-mx8m)). The tauri team is considering forking it, would you accept a PR to use it instead of the outdated crate? We could also merge it with [win7-notifications](https://github.com/tauri-apps/win7-notifications) to add Windows 7 support to notify-rust.

**Comment by hoodie** [comment]
sounds good to me

**Comment by lucasfernog** [comment]
We're discussing which windows-rs version it should use. v0.34 still compiles on Rust 1.56 (the current MSRV for notify-rust) but latest version requires Rust 1.59. Do you have an opinion on this? Should we keep the MSRV as is?

**Comment by hoodie** [comment]
we can have a separate MSRV for windows if necessary

**Comment by lucasfernog** [comment]
Ok we'll publish our fork soon.

**Comment by lucasfernog** [comment]
Fork published: https://crates.io/crates/tauri-winrt-notification do you want me to submit a PR?
