### ISSUE TITLE
Recent msrv change should have been in a minor release instead of a patch

### ISSUE THREAD

**Issue by amrbashir** [hoodie/notify-rust#151]
### Problem

With the recent version v4.5.9, the MSRV for `notify-rust` has been raised to 1.60 in react to bumping `zbus` to v3 which requires rust 1.60, but this caused downstream apps to break on older rust version unexpectedly. MSRV should have been in a minor release at least if not major.

Having a MSRV 1.60 also means that you can't submit any app that depends on it to debian store since debian only has 1.59.

### What is the solution?
`notify-rust` should revert the `zbus` bump, revert the MSRV to the version it was before and release a patch release. If you still want to use `zbus@v3` then it should be bumped in a minor release or stay on `zbus@v2` until 1.60 is available in debian

**Comment by hoodie** [comment]
that's a shame, thanks for the notice. What about using the dbus feature for this use case? zbus is always a bit "bleeding edge" in regard to MSRV, that's why I kept the old dbus-rs implementation around.

**Comment by amrbashir** [comment]
Even if we would fallback to using dbus feature, we can't build the crate because it is locked in `Cargo.toml` to `1.60`. 

My personal suggestion would be, to stay on a 1.59 complaiant version of zbus and update it once 1.60 is available in debian.

**Comment by hoodie** [comment]
since this is a reoccurring issue, do you know of any way we could check this debian compatibility in CI, other than continuously checking which rust version is packaged with debian?

**Comment by hoodie** [comment]
I'll revert the set `rust-version` to `1.59.0` knowing that the zbus feature can't build with this, it needs at least `1.60.0`. It is rather hard to keep up with which version of zbus is compatible with which version of debian from the perspective of a library that hasn't any control over either.

I would therefore try to keep compatible with zbus's latest requirements in CI (setting the rust version to 1.60) but keep the dbus version around and have it determine the cargo.toml `rust-version` just for debian.
