### ISSUE TITLE
Drop dbus crate support

### ISSUE THREAD

**Issue by flukejones** [hoodie/notify-rust#158]
I don' think there is much call to have the dbus crate when zbus is at feature parity or better.

Should it be dropped?

**Comment by hoodie** [comment]
At the moment it doesn't seem to me that it has a bunch of downsides to keep it around and it offers a fallback for certain platforms.

**Comment by jkelleyrtp** [comment]
It doesn't support iOS which is blocking support in Dioxus land.

**Comment by hoodie** [comment]
@jkelleyrtp dbus/zbus has nothing to do with iOS or macOS. Those crates aren't even compiled at on those platforms.

**Comment by hoodie** [comment]
no, keeping as fallback
