### ISSUE TITLE
Cannot handle gdbus CLI notifications

### ISSUE THREAD

**Issue by bsilvereagle** [hoodie/notify-rust#19]
1. Launch `dbus-monitor`: ` 
dbus-monitor --session "interface='org.freedesktop.Notifications'"
`
2. Send notification from the CLI (Change `/path/to/icon.png`):
```
gdbus call --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications --method org.freedesktop.Notifications.Notify gdbus "1" /path/to/icon.png Volume "69%" '[]' '{"urgency": <byte 0>}' 'int32 1000' 
```

3. Notice `dbus-monitor` output, specifically that there is an empty array specifying the actions:
```
   string "gdbus"
   uint32 1
   string "/usr/share/icons/Vibrancy-Colors/status/96/audio-volume-medium.png"
   string "Volume"
   string "69%"
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 0
      )
   ]
   int32 1000
```

4. Run toastify as a server: `toastify server`
5. Repeat Step 2.
6. Notice `toastify` crash & that the output from `dbus-monitor` now shows a string instead of an empty array:
```
   string "gdbus"
   int32 1
   string "/usr/share/icons/Vibrancy-Colors/status/96/audio-volume-medium.png"
   string "Volume"
   string "69%"
   string "[]"
   array [
      dict entry(
         string "urgency"
         variant             byte 0
      )
   ]
   int32 1000
```

The `libnotify-rust` crash happens at [line 84](https://github.com/hoodie/notify-rust/blob/master/src/server.rs#L84) of `server.rs`. 

In the crash case:
```
(gdb) p action_items
$2 = Str = {"[]"}
```

In the normal case:
```
(gdb) p action_items
$1 = (struct Vec<dbus::message::MessageItem> *) 0x7ffff5ffd6d8
```

What is particularly odd to me is that having `toastify server` running is enough to completely change the datatype of the message showing up in `dbus-monitor`. 

Removing L83-85 and replacing with `let actions:Vec<String> = vec![]` fixes the crash, but not the wrong datatype in `dbus-monitor`.

**Comment by hoodie** [comment]
Thank you for this detailed analysis, this is quite a curious bug. I hope you don't rely on the server implementation anywhere, because as I stated somewhere in the documentation: it is very experimental 😀 
Do you think you have narrowed it down close enough to provide a solution?
Otherwise I could take a look at it in a couple of days.

**Comment by bsilvereagle** [comment]
I opened an issue and not a PR since I couldn't narrow it down enough :)

My first thought was that there was a bug in gdbus, but, as you can see, the problem *only* exists when toastify is the server. I have no idea why the output from `gdbus-monitor` changes when toastify is running. 

The next place I'd look is in whatever creates the msg in the closure containing lines 83-85. I picked up Rust this morning, and it's very slow going debugging with gdb in a library you didn't write in a language you don't really know!

**Comment by hoodie** [comment]
Fair enough. I suggest, don't waste too much of your weekend on it, I didn't give the server part of this library too much attention, it was mostly implemented for testing the client side 😀 I'm gonna give it a look soon and come back to you, it's a weird bug that might just as well be a result of how strange an API dbus actually is.
