### ISSUE TITLE
throw error when build example

### ISSUE THREAD

**Issue by uncode** [hoodie/notify-rust#20]
1. run example 1 on  rustc 1.16.0-nightly (4ecc85beb 2016-12-28)

2.run `cargo run --release`

I got the message 
`
rror[E0432]: unresolved import `dbus::Error`
  --> /Users/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-rust-3.2.1/src/lib.rs:93:9
   |
93 | pub use dbus::Error;
   |         ^^^^^^^^^^^ Did you mean `server::dbus`?

error[E0432]: unresolved import `dbus::MessageItem`
 --> /Users/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-rust-3.2.1/src/util.rs:2:5
  |
2 | use dbus::MessageItem;
  |     ^^^^^^^^^^^^^^^^^ Did you mean `server::dbus`?

error[E0432]: unresolved import `dbus::Connection`
  --> /Users/leo/.cargo/registry/src/github.com-1ecc6299db9ec823/notify-rust-3.2.1/src/server.rs:15:12
   |
15 | use dbus::{Connection, BusType, NameFlag, ConnectionItem, Message, MessageItem};
   |            ^^^^^^^^^^ Did you mean `self::dbus`?

and more like following

error[E0412]: unresolved type `Message`
error[E0433]: failed to resolve. Use of undeclared type or module `MessageItem`
error[E0433]: failed to resolve. Use of undeclared type or module `ConnectionItem`

**Comment by hoodie** [comment]
Thanks for the issue, I'll look into it this weekend

**Comment by hoodie** [comment]
In fact, this looks like your build setup just can't find the dbus crate, could you try to give more explicit steps to reproduce this?
