### ISSUE TITLE
Closing a notification programmatically

### ISSUE THREAD

**Issue by e-tho** [hoodie/notify-rust#226]
I would like to be able to programmatically close a notification once an action is completed in my application, rather than relying on a timeout. 
This crate does not seem to provide a way to do this, is this an XDG limitation?

**Comment by WintersMichael** [comment]
https://docs.rs/notify-rust/latest/notify_rust/struct.NotificationHandle.html#method.close

**Comment by e-tho** [comment]
I should've RTFM, thanks.
