### ISSUE TITLE
make timeout a type

### ISSUE THREAD

**Issue by hoodie** [hoodie/notify-rust#23]
Make `Timeout` an `enum {Default, Never, Milliseconds(u32), Duration}` what ever
`.timeout()` can be made into a generic method, so no breakage, accepting `Into<Timeout>`.

**Comment by vbuell** [comment]
Should this be closed? 'Timeout' is already an enum in current codebase.

**Comment by hoodie** [comment]
Yap, I opened this as a note to myself
