### ISSUE TITLE
allow to update/replace by returned id

### ISSUE THREAD

**Issue by farseerfc** [hoodie/notify-rust#3]
Thank you to write this great lib. 
I am writing a [small tool](https://github.com/farseerfc/ydcv-rs) that uses your lib.
It will be great if I can update an existing notification using returned id.

I am not familiar with the source code, but I think it need to add a field to fill in here:
https://github.com/hoodie/notify-rust/blob/master/src/lib.rs#L314

Thank you

**Comment by hoodie** [comment]
Hi, thanks for the feedback!
I have this feature on my agenda already, the notification standard allows it.
I'll try to implement it soon.

**Comment by hoodie** [comment]
There we go! v0.9.0 supports updating :smile: 
You should look out though, the behavior of different desktop environments, implementing this functionality may vary. I tested it on xfce and kde myself, you can find notes on that in the updated doc.

have fun :cake:

**Comment by farseerfc** [comment]
Thank your for quick response! 
I have updated my toy to use update of v0.9.0.
