### ISSUE TITLE
NotificationHandle is unreachable

### ISSUE THREAD

**Issue by hasufell** [hoodie/notify-rust#32]
You provide 2 functions that return `Result<NotificationHandle>`
https://docs.rs/notify-rust/3.4.0/notify_rust/struct.Notification.html#method.show
https://docs.rs/notify-rust/3.4.0/notify_rust/struct.Notification.html#method.show_debug

but you provide no way to actually use the NotificationHandle type. Why? What is the result for if I cannot use it anyway? I can't even declare functions that return it.

**Comment by hoodie** [comment]
Thanks for catching this, this seems to be a refactoring oversight.
The handle keeps a dbus conneciton alive and is used to [update notifications](https://github.com/hoodie/notify-rust/blob/master/examples/update.rs). This was necessary on gnome. During refactoring for the macOS integration I must have forgotten to pass this through.
