### ISSUE TITLE
subsequent notifications on the same Notification object misbehave

### ISSUE THREAD

**Issue by hasufell** [hoodie/notify-rust#33]
For the rust program, two notification popups will show up, for the C program the existent popup will be updated, which is the expected behavior.

C program:
```C
#include <libnotify/notify.h>

void main() {
	notify_init("Foo");

	NotifyNotification *notification;

	notification = notify_notification_new("", NULL, NULL);
	notify_notification_set_timeout(notification, 1500);
	notify_notification_set_hint(notification, "x-canonical-private-synchronous", g_variant_new_string(""));

	notify_notification_update(notification, "blah", NULL, "audio-volume-medium");
	notify_notification_set_hint(notification, "value", g_variant_new_int32(60));

	notify_notification_show(notification, NULL);
	sleep(1);

	notify_notification_set_hint(notification, "value", g_variant_new_int32(80));

	notify_notification_show(notification, NULL);
}
```

equivalent rust program:

```rust
extern crate notify_rust;
use notify_rust::*;
use std::time::Duration;
use std::thread;

fn main() {
    let mut notify = Notification::new();

    notify
        .appname("Foo")
        .timeout(1500)
        .hint(NotificationHint::Custom(String::from("x-canonical-private-synchronous"), String::from("")))
        .hint(NotificationHint::CustomInt(String::from("value"), 60))
        .summary("blah")
        .icon("audio-volume-medium");

    notify.show().unwrap();

    thread::sleep(Duration::from_millis(1000));

    notify
        .hint(NotificationHint::CustomInt(String::from("value"), 80));

    notify.show().unwrap();
}
```

**Comment by hoodie** [comment]
The semantics here are different then in the C implementation. I did not try to copy libnotify. Here `.show()` should always produce a new pop up. For the other usecase refer to `.update()`.

**Comment by hasufell** [comment]
I don't see any such function https://docs.rs/notify-rust/3.4.0/notify_rust/fn.handle_actions.html?search=update

**Comment by hoodie** [comment]
That is most likely due to the other issue you reported. You could go ahead and check out the current master. This should fix that. But I can't test and release that myself at the moment.

**Comment by hoodie** [comment]
I just published an updated version where this is fixed. As I assumed the functionality as still there, it did just not show up in the documentation, as I was essentially leaking a private type there.
So now you can find that here https://docs.rs/notify-rust/3.4.1/notify_rust/?search=update
