### ISSUE TITLE
Windows Support?

### ISSUE THREAD

**Issue by ishanjain28** [hoodie/notify-rust#37]
Do you have any plans to add Windows Support? I am a beginner in Rust and I was looking for a library to send notifications on Windows but I could not find anything. 

I read about it a bit and there are system calls that you need to make to send different types of notifications. The `WinAPI` crate probably has support for all the syscalls we'll need for this library(or if it doesn't has some syscalls, I can create issues for it there and work that out.).
So, It should not be difficult to add windows support in this library. 

I can start working on this If you are interested in adding windows support to this library.

**Comment by hoodie** [comment]
Hi, I have thought about windows support but never found the time. I would appreciate your contribution and even buy you a beer 😁
Afaik there is already a crate that uses notify-rust and implements it's own windows notifications, perhaps you could use this as starting point. I think it was https://github.com/frewsxcv/alert-after

**Comment by Boscop** [comment]
I'm also interested in this :)

**Comment by ishanjain28** [comment]
@Boscop Sure, We can work together on this if you are interested. I found some information about notifications in windows [here](https://msdn.microsoft.com/en-us/library/windows/desktop/ee330740(v=vs.85).aspx).

**Comment by ishanjain28** [comment]
I checked winapi source code. They are currently rewriting/refactoring WinAPI and the version 0.3.0 doesn't has `shell32` code which is required to send notifications. 

The latest version on crates.io is 0.2.8 which had a modular structure. So, If I want to use `shell32`, I'll have to install `winapi` and `shell32-sys` crate. A lot of code in `shell32-sys` has been commented out for some reason(I forgot what was it exactly) and there is no documentation available for it. 

Some people in IRC have recommended to wait until they shell32 support is added to version 0.3. So, I'll wait until shell32 code is added to winapi and then start working on this. Until then, I'll just keep this issue open.

**Comment by Boscop** [comment]
Any update on this? :)

**Comment by hoodie** [comment]
hey, thanks for the reminder - I had started on just integrating an existing winrt-toast-notification crate here: https://github.com/hoodie/notify-rust/tree/feature/winwin
Hopefully I get to work on this again tomorrow.

**Comment by Boscop** [comment]
@ishanjain28 Btw, all the shell32 stuff from shell32-sys is now in winapi 3 directly.

**Comment by hoodie** [comment]
quote from the `winrt-notifications` crate: "Tested in windows 10. Untested in Windows 8 and 8.1, might work." :D

**Comment by Boscop** [comment]
@hoodie Yea but I tested it and it doesn't work on Win 8.1 https://github.com/allenbenz/winrt-notification/issues/3

**Comment by ishanjain28** [comment]
@hoodie  @Boscop  Hey, Apologies for the delay. 

winapi-rs 0.3 was released recently, I have my exams going on but I can start working on this in a few days. I hope it's okay.

**Comment by hoodie** [comment]
@ishanjain28 what is the strategie here? will you work on making winrt-notifications work on win8.1? I think this would have the most positive impact.

**Comment by allenbenz** [comment]
winrt-notifications was fixed and works on 8.1.

**Comment by hoodie** [comment]
@allenbenz, @ishanjain28 wanna play around with my `feature/winwin` branch? I currently have no windows machine handy

**Comment by allenbenz** [comment]
@hoodie I think I'll have some time next week, definitely not this weekend.

**Comment by LiHRaM** [comment]
@hoodie `feature/winwin` works on mine machine.

```cmd
> ver
Microsoft Windows [Version 10.0.19041.21]
```
All the examples compile, although [update.rs](https://github.com/hoodie/notify-rust/blob/feature/winwin/examples/update.rs) requires elevated rights.

HTML Elements do not modify the output, see e.g. the toast notification from [formatting.rs](https://github.com/hoodie/notify-rust/blob/feature/winwin/examples/formatting.rs): 
![image](https://user-images.githubusercontent.com/25297553/73543740-e7bc7880-4437-11ea-832c-61c0e677a669.png)

**Comment by hoodie** [comment]
wow, that is great to know, thanks. I don't own a single windows machine - so I can't test it manually unfortunately. I think I meant to release a 4.0.0, we could rebase that branch afterwards and try to make it a "experimental feature"

**Comment by lucasfernog** [comment]
I'm very interesting in this feature, and I can contribute too, I have the three major platforms and the Tauri community would love this!

**Comment by hoodie** [comment]
yay cool, can you rebase on the latest master?

**Comment by lucasfernog** [comment]
Gonna do it tomorrow.

**Comment by lucasfernog** [comment]
@hoodie Done, what's next?

**Comment by hoodie** [comment]
well, I can't test it on windows, so you're gonna have to promise me it works on windows, I try to review it this weekend and make a release of `4.0.0-beta.4` once that is satisfactory we should release `4.0.0` finally

**Comment by hoodie** [comment]
oh and also: thanks for keeping an eye on the conventional commit messages, but it would be great if you could make it a PR against master :grinning:

**Comment by lucasfernog** [comment]
Oops forgot to change that. We also need to check what API we are missing on Windows and see if I can implement that.

**Comment by lucasfernog** [comment]
And about testing, I think this library will have a lot of Tauri users so we'll get it better and make it bullet proof.
