### ISSUE TITLE
All dependencies are outdated

### ISSUE THREAD

**Issue by thebitstick** [hoodie/notify-rust#44]
Please consider updating the `dbus` crate from 0.4.1 to 0.6.3.

Currently when compiling there is a warning about a "redundant linker flag" for `dbus`, that has been resolved in newer versions of the `dbus` crate.
Also security issues and such, but this redundant linker flag is much more important.
Also `image` crate from 0.19 to 0.20.0.
Also `lazy_static` crate from 1.0 to 1.1.0.

**Comment by hoodie** [comment]
thank you - I've been putting this off for some time, updating to 0.6.x of dbus would require significant changes, so I was always weary of updating that. Basically the server module would have to be completely rewritten.

**Comment by hoodie** [comment]
I guess it's finally time to do this

**Comment by thebitstick** [comment]
Why would it need to be rewritten?

**Comment by hoodie** [comment]
the API of dbus-rs change significantly in 0.6

**Comment by thebitstick** [comment]
Will do
