### ISSUE TITLE
migrate to failure

### ISSUE THREAD

**Issue by hoodie** [hoodie/notify-rust#49]
* [ ] drop `error_chain` and use `failure` instead
* [ ] ⚠️ stay compatible with dependent crates!!!!!

**Comment by mkroehnert** [comment]
Hi, I just had a look at #50 and noticed that mac-notification-sys 2.0 uses failure 0.1.1.
Would this mean, that this ticket must be solved first? Or should both be resolved at the same time?

**Comment by hoodie** [comment]
Hi there, sorry for letting this dry-age for so long.
**TLDR** yes it does - I'll try to look at it this week

It's all a bit unfortunate IIRC
mac-notification-sys fixed that issue and migrated to failure at the same time. that caused some issues when I tried to update the dependecy here and therefore I had to migrate to failure too. that was not possible at the time because the dbus erros weren't thread safe or something like that, so I had to updated that too :grin: 
AFAIK the feature/failure branch should make it possible to update mac-notification-sys, I need to take another look at it though

**Comment by mkroehnert** [comment]
Thanks for the update @hoodie.
Anything I can help with? Programming, testing, ...?

**Comment by hoodie** [comment]
Thanks, I'll have to checkout `feature/failure` again, after forgetting about it for a while.
My biggest concern is that migrating to `failure` proofs to be a breaking change, that would be a big NoNo in my opinion. I'll probably also have to check lots of the users of this lib on crates.io to see if they rely on the errors being in a certain format ATM, otherwise this could probably slip by unnoticed

**Comment by hoodie** [comment]
I just spent some time trying to shoehorn the failure migration into a backward compatible version. Seems to be too weird. If you could perhaps review #52

**Comment by hoodie** [comment]
nope no longer want to do this, using native errors instead
