### ISSUE TITLE
notification size?

### ISSUE THREAD

**Issue by PrismaPhonic** [hoodie/notify-rust#51]
Hi, I did already see this ticket: https://github.com/hoodie/notify-rust/issues/31 but saw the issue has already been closed and isn't my exact problem.  I'm specifically wondering if it's possible to change notification size in general (text size and icon size).  On my 4K laptop the notification is extremely tiny - it's way smaller than the notifications I get from any other application - so I don't think it's a system limitation.  Any idea of how to bump up the size of the notification?  Or maybe just to get it to respect scaling set within a linux system?

I'm using Arch Linux

**Comment by hoodie** [comment]
I'm gonna close this, since I don't see anything we can do in the lib ATM
