### ISSUE TITLE
How to get sound_name to work?

### ISSUE THREAD

**Issue by UnicodeAlt255** [hoodie/notify-rust#58]
I'm on Arch, and have `sound-theme-freedesktop` installed, and all the sounds can be found in `/usr/share/sounds/freedesktop/stereo`. 

I'm using the convenience method `sound_name` in the builder pattern and passing `"alarm-clock-elapsed"`, which should play the sound `/usr/share/sounds/freedesktop/stereo/alarm-clock-elapsed.oga`. 

However, it just doesn't seem to work. I made sure my sound was all the way up and every other sound is normally working. I understand that not all features may work, but I'm curious as to how anyone else has gotten it working? Am I missing something here?

I've tried on dunst, xfce4-notifyd, lxqt-notificationd, and mate-notification-daemon. https://wiki.archlinux.org/index.php/Desktop_notifications#Notification_servers

**Comment by hoodie** [comment]
TBO I never really go that to work, it's either broken in my implementation or it's just specified, but non of the servers actually implement it 🤷‍♂

**Comment by UnicodeAlt255** [comment]
I'm going to try to get it implemented in dunst, but that'll take a while, you can close this issue if you would like.

**Comment by hoodie** [comment]
sure, let me know if you figure something out thanks :)
