### ISSUE TITLE
NotificationClosed not received on timeout by gnome notification-daemon

### ISSUE THREAD

**Issue by panicbit** [hoodie/notify-rust#6]
I'm not sure whether we can fix this or if this is a bug in the gnome `notification-daemon` but when a notification times out we don't receive a `NotificationClosed` signal (i.e. the `wait_for_close` example does not finish when the notification times out).
Note, however, that this works properly with `mate-notification-daemon` and `dunst`.

*EDIT:*
Turns out that `notification-daemon` only emits `NotificationClosed` for timeouts when the notification is transient... The spec sadly doesn't mention much on this topic.

**Comment by hoodie** [comment]
Ah, selfclosing issues :stuck_out_tongue_winking_eye:
