### ISSUE TITLE
Update to dbus 0.7.x

### ISSUE THREAD

**Issue by danieldulaney** [hoodie/notify-rust#64]
It looks like the dbus dependency made breaking changes between their 0.6 and 0.7 releases, with a plan to deprecate the current `MessageItem`-based API.

This is an issue for crates that want to use both notify-rust and a newer version of dbus, because the two versions cannot coexist -- they each attempt to independently link to the dbus native library.

**Comment by hoodie** [comment]
Thanks for pointing that out. #63 already [showed](https://travis-ci.org/hoodie/notify-rust/builds/596962515?utm_source=github_status&utm_medium=notification) that I can't trivially update. I intend to update, but I'm not sure I can make it soon.

**Comment by hoodie** [comment]
wow, awesome! thanks

**Comment by danieldulaney** [comment]
No worries! I didn't see #63 -- edited the PR to mention it. There are a couple of (genuinely very small) breaking changes, so let me know if there's something different you want to do there.

**Comment by hoodie** [comment]
as already mentioned on the PR, do you think it is impossible to update without breaking changes?

**Comment by hoodie** [comment]
thanks for the patients, I haven't had much time lately. I just released a `4.0.0-alpha` if you'd like to check it out
