### ISSUE TITLE
4.0.0-beta.1 does not export NotificationHandle

### ISSUE THREAD

**Issue by jonhoo** [hoodie/notify-rust#67]
I think the re-export was accidentally removed in a1b2b9af8e936d479dd4c8066e22b62a62adb589

**Comment by hoodie** [comment]
that was quick, thanks for the feedback, were you already using the 4.0.0  alpha?

**Comment by jonhoo** [comment]
Hehe, nope, I just randomly tried to jump on `4.0.0` when it shows up in `cargo outdated` just now :)

**Comment by hoodie** [comment]
rainy sunday afternoon heh?
I just pushed a beta.2, thanks for the feedback, keep em coming
