### ISSUE TITLE
Support action to enter text in notification box

### ISSUE THREAD

**Issue by clearnote01** [hoodie/notify-rust#71]
I am not sure if it's even possible but I would love to see a feature like this. It opens up a lot of options for an application ex- replying to IMs with mentions without open the App, searching for song and playing from notification directly,

**Comment by hoodie** [comment]
I'm not aware if this is supported. This crate is basically a client to given desktop APIs and doesn't implement any of the rendering or interaction itself. The XDG (KDE, Gnome etc) interface allows buttons, but AFAIK no text input. Mac is a very thin layer and cannot do more than simple notifications. The Windows API might be able to do more, but I'm trying to provide only the shared feature set for better portability in this one.

**Comment by clearnote01** [comment]
Yes, makes sense, closing this.
