### ISSUE TITLE
Understanding notification image data

### ISSUE THREAD

**Issue by mtshrmn** [hoodie/notify-rust#81]
I don't seem to understand how to set an image for a notification. The examples provide the following API:
```rust
Notification::new().hint(Hint::ImageData(image));
// and
Notification::new().image_data(image);
```
But there's nothing about it in the documentation. How can I set an image for the notification?
I've tried creating a temporary image and pass the path to `Hint::ImagePath` or `image_path`, but the notification won't display it. It might be because the image gets deleted as soon as the program exists the scope. 

Please help me understand it.

**Comment by hoodie** [comment]
This only works on xdg desktops (gnome, kde, etc). I think [the images example](https://github.com/hoodie/notify-rust/blob/main/examples/images.rs) should cover all possible ways to display an image. If you don't see anything then it might be an issue with your desktop environment or a compatibility issue. What desktop environment are you using?

**Comment by mtshrmn** [comment]
I'm using i3 with dunst as the notification server.
While trying to create an example code for this issue, I found out I just made a mistake and forgot to "creating a temporary image" as I've stated in the issue. I can add an image to a notification with the method I've described without any issue.

This leaves me with one question - the `image_data()` function which exists in the examples doesn't seem to exist:
```
error[E0599]: no method named `image_data` found for mutable reference `&mut notify_rust::notification::Notification` in the current scope
  --> src/main.rs:42:39
   |
42 |     Notification::new().summary("yes").image_data().show().unwrap();
   |                                       ^^^^^^^^^^ help: there is an associated function with a similar name: `image_path`
```

**Comment by hoodie** [comment]
did you enable the feature?

**Comment by mtshrmn** [comment]
Ok I see, this is what I was doing wrong. I wasn't using it. Thanks for clearing that up.
