### ISSUE TITLE
Support for musl

### ISSUE THREAD

**Issue by timvisee** [hoodie/notify-rust#85]
Compiling for the `x86_64-unknown-linux-musl` target succeeds, but invoking `show()` on a notification causes a segfault at runtime.

How would I use `notify-rust` on `musl`? Are there any plans to support this?

Give it a try with:
```bash
PKG_CONFIG_ALLOW_CROSS=1 cargo run --target="x86_64-unknown-linux-musl" --example simple
```

**Comment by hoodie** [comment]
Up until now notify-rust relied solely on `dbus-rs` (which links to libdbus), so musl wasn't possible.
Luckily we now have an alternative with zbus (a selfcontained pure rust dbus implementation).
So I just tried it out and it seems to work.

try something like this:
```
cargo run --target x86_64-unknown-linux-musl --no-default-features --features z --example simple
```

**Comment by hoodie** [comment]
I'd consider this solved, thanks for bringing it up
