### ISSUE TITLE
Hint::CustomInt doesn't work well

### ISSUE THREAD

**Issue by mrlogick** [hoodie/notify-rust#88]
I'm on archlinux, i3wm, xfce4-notifyd. If I just show the bar there are no problems.
But if I update the value quickly the bar goes crazy. it's not fluid. It even goes back sometimes.
```
extern crate notify_rust;
fn main() {
    let mut notification = notify_rust::Notification::new().show().unwrap();
    for i in 0..100 {
        notification.hint(notify_rust::Hint::CustomInt("value".to_string(), i));
        std::thread::sleep(std::time::Duration::from_millis(100));
        notification.update();
    }
}
```

**Comment by hoodie** [comment]
thanks for the find, this is a fun one!
What happens is that everytime you call `.hint(...)` it inserts another `CustomInt` into the list. So with each `.update()` you actually send all previews values of `CustomInt`s and one more. It is up to the actual implementation of the desktop (notify-rust doesn't render anything) to interpret how to render a notification with many values. I suppose it just renders the last one in the list.

**Comment by mrlogick** [comment]
I understand. Is there any way around this? to make the bar look smooth?
